global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'cadvisor:8090' ]

  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'app:8080' ]